//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSchedule.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> idTrain { get; set; }
        public Nullable<int> idPassenger { get; set; }
    
        public virtual Pessenger Pessenger { get; set; }
        public virtual Train Train { get; set; }
    }
}
